development:
  adapter: postgresql
  database: laguna
  username: livia
  password: livia

test:
  adapter: postgresql
  database: laguna
  username: livia
  password: livia

production:
  adapter: postgresql
  database: laguna
  username: livia
  password: livia

